### PR TITLE
Video docs fixes

### PR DESCRIPTION
**Pull request by probicheaux**
Lots of updates based on Inference user sessions:

- Big docs refactor to separate docs content from tutorial content
- Added comments to most code snippets for clarity
- Added quickstart tutorial for how to make a custom inference pipeline sink
- Vastly simplified the main left nav (including making the home page its own page with no left nav)
- Added a new built in sink for saving video files with the inference pipelines
- Fixed lots of broken links
- Made all external links open a new tab
- Updated all internal links to be relative
- Added inference-cli as an install requirement for inference, so now there is no need to separately pip install inference-cli
- Added some templating so we don't copy/paste but can still include common instructions (i.e. install instructions) in several places
- Made top nav links larger / more obvious

### CODE REVIEW

**Comment by capjamesg** [comment]
@probicheaux I am getting an error when running `mkdocs serve`:

```
ERROR   -  Error reading page 'docs/reference/inference/enterprise/parallel/infer.md': list index out of range
Traceback (most recent call last):
  File "/opt/homebrew/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/commands/build.py", line 175, in _populate_page
    page.render(config, files)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/structure/pages.py", line 271, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/markdown/core.py", line 254, in convert
    root = self.parser.parseDocument(self.lines).getroot()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/markdown/blockparser.py", line 84, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/opt/homebrew/lib/python3.11/site-packages/markdown/blockparser.py", line 99, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/opt/homebrew/lib/python3.11/site-packages/markdown/blockparser.py", line 117, in parseBlocks
    if processor.run(parent, blocks) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings/extension.py", line 127, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings/extension.py", line 213, in _process_block
    rendered = handler.render(data, options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/handler.py", line 328, in render
    return template.render(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/homebrew/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/module.html", line 1, in top-level template code
    {% extends "_base/module.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/_base/module.html", line 55, in top-level template code
    {% block contents scoped %}
^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/_base/module.html", line 62, in block 'contents'
    {% block children scoped %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/_base/module.html", line 66, in block 'children'
    {% include "children.html" with context %}
^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/children.html", line 1, in top-level template code
    {% extends "_base/children.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/_base/children.html", line 76, in top-level template code
    {% include function|get_template with context %}
^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/function.html", line 1, in top-level template code
    {% extends "_base/function.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/_base/function.html", line 66, in top-level template code
    {% block contents scoped %}
^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/_base/function.html", line 67, in block 'contents'
    {% block docstring scoped %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/_base/function.html", line 67, in block 'docstring'
    {% block docstring scoped %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/griffe/dataclasses.py", line 150, in parsed
    return self.parse()
           ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/griffe/dataclasses.py", line 163, in parse
    return parse(self, parser or self.parser, **(options or self.parser_options))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/griffe/docstrings/parsers.py", line 51, in parse
    return parsers[parser](docstring, **options)  # type: ignore[operator]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/griffe/docstrings/google.py", line 686, in parse
    section, offset = reader(docstring, offset=offset + 1, **options)  # type: ignore[operator]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/griffe/docstrings/google.py", line 384, in _read_returns_section
    annotation = annotation.tuple_item(index)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/griffe/expressions.py", line 248, in tuple_item
    return self.non_optional[2][2 * nth]
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
IndexError: list index out of range
```

**Comment by capjamesg** [comment]
We should remove the `find_and_replace_links.py` file from the root directory. If it is a one-off script that we no longer need, we can remove it from the repository. Otherwise, it can go in the `docs` folder.

**Comment by paulguerrie** [comment]
@capjamesg I removed the utility script that I accidentally versioned, good catch!

I can't reproduce your mkdocs error. Can you try running in a fresh virtual environment and start by running `pip install -r requirements/requirements.docs.txt`. Then run `mkdocs serve` and see if it works?

**Review by capjamesg — APPROVED** [review]
@probicheaux Amazing work on this PR. The documentation looks and feels great. I'm glad we have a tutorial on inference sinks now. I found myself thinking about that topic earlier today, wondering to where I should go for an introduction!

**Pull request merged**
