### PR TITLE
add bounding box measurement block

### PR DESCRIPTION
**Pull request by ryanjball**
# Description

Outputs measurements in mm/inches based on reference object pixel/measurement ratio

List any dependencies that are required for this change.

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ X] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

### CODE REVIEW

**Comment by grzegorz-roboflow** [comment]
@ryanjball , great idea! Do you envision field of view to be always supporting constant pixels-to-inch ratio? Also, for countries with dominant metric systems, would be great to add second output in meters.

**Comment by PawelPeczek-Roboflow** [comment]
@ryanjball let's try to push with this block to avoid rush at the end of the week

**Comment by PawelPeczek-Roboflow** [comment]
@ryanjball if the block is not sorted out end of day today it will land in release `0.22.0`

**Comment by PawelPeczek-Roboflow** [comment]
pushed to next release

**Comment by PawelPeczek-Roboflow** [comment]
Closing in favour of https://github.com/roboflow/inference/pull/713

**Pull request closed without merging**
