### PR TITLE
Expand supervision support to 0.30.0

### PR DESCRIPTION
**Pull request by LinasKo**
# Description

Supervision has a policy where deprecations are announced 5 releases in advance.

This PR makes the single change required to support supervision up to release `0.30.0` based on the [planned deprecations](https://supervision.roboflow.com/latest/deprecated/). However, we expect to move to `1.0.0` before `0.30.0`.

Changes:
* Updated InferenceSlicer parameter (deprecated in `0.27.0`)
* Bumped lower supervision bound to `0.25.1` (dependency versions, specifically addressing `numpy` version clash)
* Bumped upper version to `0.30.0` (safe to do due to deprecation policy)

Note: this PR uses the corrected variable name `overlap_filter` - I left a mistake in the deprecations doc.

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

* I used `inference` with `supervision` throughout this release, from a custom inference branch, which permits latest supervision version.
* I installed supervision together with changes in this PR and checked that models can be run (Py 3.10).

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by LinasKo** [comment]
I see the dependency clashes @PawelPeczek-Roboflow, I'll look into it.

**Review by PawelPeczek-Roboflow — APPROVED** [review]

**Comment by LinasKo** [comment]
Regarding the failing ByteTrack test, I update `ByteTrack` in `supervision 0.25.0`, so they do not share any values. If you had a special case for tracking, you shouldn't need it anymore.

**Comment by LinasKo** [comment]
I'm fine with that.

This would leave a TODO to nuke `InstanceCache` in ByteTracker Blocks later on.

**Review by PawelPeczek-Roboflow — APPROVED** [review]

**Comment by LinasKo** [comment]
Thank you!

**Pull request merged**
