### PR TITLE
Automated PyPI Publishing

### PR DESCRIPTION
**Pull request by paulguerrie**
# Description

Adds a github action to automatically publish wheels to PyPI whenever a new release is created.

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Tested with `gh act relsease` locally

### CODE REVIEW

**Comment by capjamesg** [comment]
I ran `gh act release` and saw no errors or output. Is this expected? If so, looks good.

**Comment by capjamesg** [comment]
Also to review this PR you will need the GitHub CLI installed and the `act` extension:

```
brew install gh
gh auth login
gh extension install https://github.com/nektos/gh-act
gh act release
```

**Comment by capjamesg** [comment]
The following command doesn't return any output:

```
gh act -s GITHUB_TOKEN="$(gh auth token)" release --container-architecture linux/amd64
```

**Comment by capjamesg** [comment]
I'm getting:

```
[Publish WorkFlow/build]   ✅  Success - Main 🦾 Install dependencies
[Publish WorkFlow/build] ⭐ Run Main 🛞 Create Wheels to PyPi
[Publish WorkFlow/build]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=
| rm dist/*
| rm: cannot remove 'dist/*': No such file or directory
| make: *** [Makefile:24: create_wheels] Error 1
[Publish WorkFlow/build]   ❌  Failure - Main 🛞 Create Wheels to PyPi
[Publish WorkFlow/build] exitcode '2': failure
[Publish WorkFlow/build] 🏁  Job failed
Error: Job 'build' failed
```

**Comment by paulguerrie** [comment]
> I'm getting:
> 
> ```
> [Publish WorkFlow/build]   ✅  Success - Main 🦾 Install dependencies
> [Publish WorkFlow/build] ⭐ Run Main 🛞 Create Wheels to PyPi
> [Publish WorkFlow/build]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=
> | rm dist/*
> | rm: cannot remove 'dist/*': No such file or directory
> | make: *** [Makefile:24: create_wheels] Error 1
> [Publish WorkFlow/build]   ❌  Failure - Main 🛞 Create Wheels to PyPi
> [Publish WorkFlow/build] exitcode '2': failure
> [Publish WorkFlow/build] 🏁  Job failed
> Error: Job 'build' failed
> ```

Ah good catch. Just pushed a fix.

**Comment by capjamesg** [comment]
The wheels now build, but I run into this on the upload stage:

```
[Publish WorkFlow/build]   ✅  Success - Main 🛞 Create Wheels
[Publish WorkFlow/build] ⭐ Run Main 🚀 Publish to PyPi
[Publish WorkFlow/build]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/4] user= workdir=
| twine upload dist/*.whl
| /bin/sh: 1: twine: not found
| make: *** [Makefile:31: upload_wheels] Error 127
[Publish WorkFlow/build]   ❌  Failure - Main 🚀 Publish to PyPi
[Publish WorkFlow/build] exitcode '2': failure
[Publish WorkFlow/build] 🏁  Job failed
Error: Job 'build' failed
```

It looks like `twine` isn't installed?

**Comment by paulguerrie** [comment]
> The wheels now build, but I run into this on the upload stage:
> 
> ```
> [Publish WorkFlow/build]   ✅  Success - Main 🛞 Create Wheels
> [Publish WorkFlow/build] ⭐ Run Main 🚀 Publish to PyPi
> [Publish WorkFlow/build]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/4] user= workdir=
> | twine upload dist/*.whl
> | /bin/sh: 1: twine: not found
> | make: *** [Makefile:31: upload_wheels] Error 127
> [Publish WorkFlow/build]   ❌  Failure - Main 🚀 Publish to PyPi
> [Publish WorkFlow/build] exitcode '2': failure
> [Publish WorkFlow/build] 🏁  Job failed
> Error: Job 'build' failed
> ```
> 
> It looks like `twine` isn't installed?

Just pushed a fix. Sorry, not sure why it works on my machine. It must be accessing my local environment somehow. I had assumed it was using a separate env or something.

**Review by capjamesg — APPROVED** [review]
After our discussion in Slack, I approve.

**Pull request merged**
