### PR TITLE
chore: remove supervision version block

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description

Hello 👋  It is simple fix for removing version block so that we can install supervision latest always.

### CODE REVIEW

**Comment by grzegorz-roboflow** [comment]
Might be risky when there are features staged for obsolesce in `supervision`, @PawelPeczek-Roboflow what's your opinion?

**Comment by onuralpszr** [comment]
> Might be risky when there are features staged for obsolesce in `supervision`, @PawelPeczek-Roboflow what's your opinion?

Well, I can understand that but everytime I tried to install supervision + inference I got errors or rollback to older version of sv. Also If supervision parts needs to be update I can help those (I didn't check tests so I don't how extensive they are doing tests but at least supervision and inference should align imo.

**Comment by grzegorz-roboflow** [comment]
It's more to do with the fact that some folks may be stuck with older versions of inference due to other dependencies they have - at least I think we might introduce problems hard to predict  if we remove version pin, I might be too paranoid, lets hear @PawelPeczek-Roboflow opinion

**Review by PawelPeczek-Roboflow — CHANGES_REQUESTED** [review]
manual control is required due to planned removals that happen in supervision over time - I am fine to bump to newest version if everything works, but not to remove the pin

**Comment by PawelPeczek-Roboflow** [comment]
closing in favour of PR I am just preparing with bumping up the versions

**Pull request closed without merging**
