### PR TITLE
Add lmm extras

### PR DESCRIPTION
**Pull request by probicheaux**
# Description

Add new extras `inference[lmm]` in our wheels, so our pip installs can install requirements needed to run paligemma and florence2. NOTE: Florence2 will still need flash attention to be installed somehow

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Built wheels locally

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by probicheaux** [comment]
@PawelPeczek-Roboflow can you review this

**Review by PawelPeczek-Roboflow — CHANGES_REQUESTED** [review]
* lmm seems not to be good extras name 
* there is lack of tests confirming insatiability of new extras
* there is no docs explaining how to use it - including the need for flashattn which is crutial
* all above are required for the submission to be accepted

**Comment by PawelPeczek-Roboflow** [comment]
ping

**Comment by probicheaux** [comment]
Going to branch off of https://github.com/roboflow/inference/pull/563/ which has better requirements files

**Pull request closed without merging**
