### PR TITLE
Allow configurable "labeling batch prefix" on Roboflow Dataset Upload block.

### PR DESCRIPTION
**Pull request by NickHerrig**
# Description

This PR adds the ability to configure a workflow parameter to be passed in to set the labeling batch prefix on the Roboflow Dataset Upload block. Previously, manually setting this field to `$input.batch_name` could cause the execution engine to raise a 500 error. 

## Type of change

Please delete options that are not relevant.

-   [X] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

I've tested this locally through running the inference server and uploading an image with the batch-prefix.

### CODE REVIEW

**Review by PawelPeczek-Roboflow — DISMISSED** [review]

**Comment by PawelPeczek-Roboflow** [comment]
We have a request to make predictions optional - would you be able to take it?

**Comment by NickHerrig** [comment]
@PawelPeczek-Roboflow Yeah, I can take a look at that. 
Want me to make those changes on this PR/Branch?

**Comment by PawelPeczek-Roboflow** [comment]
looks, ok - gimme sec to test it out

**Comment by PawelPeczek-Roboflow** [comment]
Ok, added tests LGTM
@grzegorz-roboflow could you review as I was the last person pushing changes?

**Review by PawelPeczek-Roboflow — APPROVED** [review]

**Review by grzegorz-roboflow — APPROVED** [review]

**Pull request merged**
