### PR TITLE
Add support for image_and_json format

### PR DESCRIPTION
**Pull request by SolomonLake**
# Description

Adds new format option for v0 http request, `image_and_json`. This will create the image visualization, and return it with the predictions json. Also updates inference_sdk to output the image in the desired format (pillow, numpy, etc).

Adding this as a separate initiative to the ongoing workflows feature improvements because it is relatively small update.

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Tested locally w/ inference_sdk, and on staging hosted API.

## Any specific deployment considerations

- hosted API

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by SolomonLake** [comment]
closing because we are adding support to workflows soon

**Comment by SolomonLake** [comment]
reopened because we don't know how long out workflows support is -- and this is a relatively small change. will need hosted API testing before rolling out.

**Review by PawelPeczek-Roboflow — COMMENTED** [review]
LGTM
❗ Please do not merge before testing in hosted platform

**Comment by PawelPeczek-Roboflow** [comment]
@SolomonLake lost that from focus for a while - what is the status here?

**Review by PawelPeczek-Roboflow — APPROVED** [review]

**Pull request merged**
