### PR TITLE
Add transformers extras

### PR DESCRIPTION
**Pull request by probicheaux**
# Description

Adds new extras install which install pytorch and other necessary dependencies for florence2, paligemma, and other transformers packages

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Locally

## Any specific deployment considerations

New extras wheel to be built

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by probicheaux** [comment]
Addressing @PawelPeczek-Roboflow 's comments from https://github.com/roboflow/inference/pull/540
- lmm seems not to be good extras name
Changed to `inference[transformers]`
- there is lack of tests confirming insatiability of new extras
Added install tests
- there is no docs explaining how to use it - including the need for flashattn which is crutial
Added a reference in the paligemma docs -- not quite sure  about
> including the need for flashattn which is crucial
not sure how or why to document this package in particular
- all above are required for the submission to be accepted

**Review by PawelPeczek-Roboflow — COMMENTED** [review]
Ok, this is good, `transformers` extras makes semantical sense. 
Could you please add the `transformers` extras to https://github.com/roboflow/inference/blob/e601ad7898e35477ee872c8e92388d5b2a56b47b/docs/models.md#L91-L90

in the previous PR u mentioned `Florence2 will still need flash attention to be installed somehow` which I also remember from fixing GPU docker build. AFAIK it must be installed after torch dependencies are resolved and basically GPU is required to run that model. Could we state that clearly as a warning in the table with extras and in any docs being entrypoint for flornce2 (do not see one, only mentioned that model is supported)

**Comment by probicheaux** [comment]
>Could you please add the transformers extras to https://github.com/roboflow/inference/blob/e601ad7898e35477ee872c8e92388d5b2a56b47b/docs/models.md#L91-L90

Added to extras table with warning about flash_attn

I forgot how much a pain that package is, we can't even install it in a fresh env becasue it needs `packaging` to install. If we want to make sure that stuff is getting installed correctly, we should probably start work on an install script for inference

**Review by PawelPeczek-Roboflow — APPROVED** [review]

**Comment by PawelPeczek-Roboflow** [comment]
@probicheaux this PR was reverted due to failing CI

**Pull request merged**
