### PR TITLE
Dont skip special tokens for florence

### PR DESCRIPTION
**Pull request by probicheaux**
# Description

Don't skip special tokens (Aka location tokens) for florence 2

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

locally

## Any specific deployment considerations

no

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Review by PawelPeczek-Roboflow — COMMENTED** [review]
looks good, but there is issue with test + linter needed

**Comment by PawelPeczek-Roboflow** [comment]
Shall we close in favour of https://github.com/roboflow/inference/pull/661?

**Comment by probicheaux** [comment]
@PawelPeczek-Roboflow , no this needs to go in as well, but the eos/bos parsing is no longer necessary

**Comment by probicheaux** [comment]
actually, I guess we can close, because that branch has these commits and changes most of the code here.

**Pull request closed without merging**
